name: 'Repo-List-Generator'
author: 'yi_Xu'
description: 'Generate repo list for user or organization.'

branding:
  icon: 'list'
  color: 'yellow'

inputs:
  user:
    description: >
      Set up the user name to generate repository list.
      It can be user or organization.
      The 'owner/repository' will transform to 'owner'.
    required: false
    default: ${{ github.repository }}
  max_page:
    description: >
      Set up maxPage for request to generate repository list.
      Default 100 repository per page can be fetched.
    required: false
    default: 10
  my_token:
    description: >
      Set up the personal access token (PAT).
      The PAT is used to generate repository list for user or organization.
    required: false
    default: ${{ github.token }}
  block_list:
    description: >
      Set up the block_list for repoList.
      The repositories in block_list will exclude in repository list.
    required: false
    default: ''
  allow_empty:
    description: >
      Set up whether allow empty repository for repoList.
    required: false
    default: false
  allow_archived:
    description: >
      Set up whether allow archived repository for repoList.
    required: false
    default: true

outputs:
  repo:
    description: >
      Current repository name.
  repoList:
    description: >
      Repository list exclude private and fork.
      Public(source without private) and no fork.
  repoList_ALL:
    description: >
      Repository list include private and fork.
      Source(public and private) and fork.
  repoList_PRIVATE:
    description: >
      Repository list include private.
      Source(public and private) and no fork.
  repoList_FORK:
    description: >
      Repository list include fork.
      Public(source without private) and fork.
  privateList:
    description: >
      Private repository list.
      Only private(fork can not be private).
  forkList:
    description: >
      Fork repository list.
      Only fork(private can not be fork).
  emptyList:
    description: >
      Empty repository list.
      Default exclude in each list.
  archivedList:
    description: >
      Archived repository list.
      Default include in each list.

runs:
  using: 'node12'
  main: 'dist/index.js'
